"""first migrations

Revision ID: af86681c81a1
Revises: 
Create Date: 2020-09-23 17:35:53.016054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af86681c81a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('level_speak', sa.Integer(), nullable=True),
    sa.Column('level_write', sa.Integer(), nullable=True),
    sa.Column('level_comprehension', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('languages')
    # ### end Alembic commands ###
